//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.25 at 12:54:27 PM PDT 
//


package ca.bc.gov.moh.rtrans.hl7.v3.service.dto;

import ca.bc.gov.moh.rtrans.entity.Person;



public class HL7Participant {

    

    protected Person target;

    protected HL7NullFlavor nullFlavor;


    protected String typeCode;

    public Person getTarget() {
        return target;
    }

    public void setTarget(Person value) {
        this.target = value;
    }

    public HL7NullFlavor getNullFlavor() {
        return nullFlavor;
    }

    public void setNullFlavor(HL7NullFlavor value) {
        this.nullFlavor = value;
    }

    public String getTypeCode() {
        return typeCode;
    }

    public void setTypeCode(String value) {
        this.typeCode = value;
    }

}
