//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.25 at 12:54:27 PM PDT 
//


package ca.bc.gov.moh.rtrans.hl7.v3.service.dto;




public class HL7QueryAck {

    protected String queryResponseCode;
    protected int resultTotalQuantity;
    protected HL7NullFlavor nullFlavor;

    public String getQueryResponseCode() {
        return queryResponseCode;
    }

    
    public void setQueryResponseCode(String value) {
        this.queryResponseCode = value;
    }

    public int getResultTotalQuantity() {
        return resultTotalQuantity;
    }

    public void setResultTotalQuantity(int value) {
        this.resultTotalQuantity = value;
    }

    public HL7NullFlavor getNullFlavor() {
        return nullFlavor;
    }

    public void setNullFlavor(HL7NullFlavor value) {
        this.nullFlavor = value;
    }

}
