//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.05 at 09:56:19 AM PDT 
//


package org.hl7.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PRPA_IN101102CA.MFMI_MT700746BC.ControlActProcess complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PRPA_IN101102CA.MFMI_MT700746BC.ControlActProcess">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/>
 *         &lt;element name="effectiveTime" type="{urn:hl7-org:v3}IVL_TS" minOccurs="0"/>
 *         &lt;element name="subject" type="{urn:hl7-org:v3}PRPA_IN101102CA.MFMI_MT700746BC.Participant" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="queryAck" type="{urn:hl7-org:v3}MFMI_MT700746BC.QueryAck" minOccurs="0"/>
 *         &lt;element name="queryByParameterPayload" type="{urn:hl7-org:v3}QUPA_MT101101BC.QueryByParameterPayload" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:hl7-org:v3}InfrastructureRootAttributes"/>
 *       &lt;attribute name="classCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="moodCode" type="{urn:hl7-org:v3}ActMood" fixed="EVN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PRPA_IN101102CA.MFMI_MT700746BC.ControlActProcess", propOrder = {
    "realmCode",
    "typeId",
    "templateId",
    "effectiveTime",
    "subject",
    "queryAck",
    "queryByParameterPayload"
})
public class PRPAIN101102CAMFMIMT700746BCControlActProcess {

    protected List<CS> realmCode;
    protected II typeId;
    protected List<II> templateId;
    protected IVLTS effectiveTime;
    @XmlElement(nillable = true)
    protected List<PRPAIN101102CAMFMIMT700746BCParticipant> subject;
    @XmlElementRef(name = "queryAck", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<MFMIMT700746BCQueryAck> queryAck;
    @XmlElementRef(name = "queryByParameterPayload", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<QUPAMT101101BCQueryByParameterPayload> queryByParameterPayload;
    @XmlAttribute(name = "classCode")
    @XmlSchemaType(name = "anySimpleType")
    protected String classCode;
    @XmlAttribute(name = "moodCode")
    protected List<String> moodCode;

    /**
     * Gets the value of the realmCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the realmCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealmCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CS }
     * 
     * 
     */
    public List<CS> getRealmCode() {
        if (realmCode == null) {
            realmCode = new ArrayList<CS>();
        }
        return this.realmCode;
    }

    /**
     * Gets the value of the typeId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setTypeId(II value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getTemplateId() {
        if (templateId == null) {
            templateId = new ArrayList<II>();
        }
        return this.templateId;
    }

    /**
     * Gets the value of the effectiveTime property.
     * 
     * @return
     *     possible object is
     *     {@link IVLTS }
     *     
     */
    public IVLTS getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * Sets the value of the effectiveTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLTS }
     *     
     */
    public void setEffectiveTime(IVLTS value) {
        this.effectiveTime = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PRPAIN101102CAMFMIMT700746BCParticipant }
     * 
     * 
     */
    public List<PRPAIN101102CAMFMIMT700746BCParticipant> getSubject() {
        if (subject == null) {
            subject = new ArrayList<PRPAIN101102CAMFMIMT700746BCParticipant>();
        }
        return this.subject;
    }

    /**
     * Gets the value of the queryAck property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MFMIMT700746BCQueryAck }{@code >}
     *     
     */
    public JAXBElement<MFMIMT700746BCQueryAck> getQueryAck() {
        return queryAck;
    }

    /**
     * Sets the value of the queryAck property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MFMIMT700746BCQueryAck }{@code >}
     *     
     */
    public void setQueryAck(JAXBElement<MFMIMT700746BCQueryAck> value) {
        this.queryAck = value;
    }

    /**
     * Gets the value of the queryByParameterPayload property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link QUPAMT101101BCQueryByParameterPayload }{@code >}
     *     
     */
    public JAXBElement<QUPAMT101101BCQueryByParameterPayload> getQueryByParameterPayload() {
        return queryByParameterPayload;
    }

    /**
     * Sets the value of the queryByParameterPayload property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link QUPAMT101101BCQueryByParameterPayload }{@code >}
     *     
     */
    public void setQueryByParameterPayload(JAXBElement<QUPAMT101101BCQueryByParameterPayload> value) {
        this.queryByParameterPayload = value;
    }

    /**
     * Gets the value of the classCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * Sets the value of the classCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassCode(String value) {
        this.classCode = value;
    }

    /**
     * Gets the value of the moodCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the moodCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMoodCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMoodCode() {
        if (moodCode == null) {
            moodCode = new ArrayList<String>();
        }
        return this.moodCode;
    }
}
