//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.05 at 09:56:19 AM PDT 
//


package org.hl7.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QUCR_MT200000BC.ParameterList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QUCR_MT200000BC.ParameterList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/>
 *         &lt;element name="coveredPartyAsPatient.Id" type="{urn:hl7-org:v3}QUCR_MT200000BC.CoveredPartyAsPatient"/>
 *         &lt;element name="policyOrAccount.Id" type="{urn:hl7-org:v3}QUCR_MT200000BC.PolicyOrAccount"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:hl7-org:v3}InfrastructureRootAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QUCR_MT200000BC.ParameterList", propOrder = {
    "realmCode",
    "typeId",
    "templateId",
    "coveredPartyAsPatientId",
    "policyOrAccountId"
})
public class QUCRMT200000BCParameterList {

    protected List<CS> realmCode;
    protected II typeId;
    protected List<II> templateId;
    @XmlElement(name = "coveredPartyAsPatient.Id", required = true, nillable = true)
    protected QUCRMT200000BCCoveredPartyAsPatient coveredPartyAsPatientId;
    @XmlElement(name = "policyOrAccount.Id", required = true, nillable = true)
    protected QUCRMT200000BCPolicyOrAccount policyOrAccountId;

    /**
     * Gets the value of the realmCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the realmCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealmCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CS }
     * 
     * 
     */
    public List<CS> getRealmCode() {
        if (realmCode == null) {
            realmCode = new ArrayList<CS>();
        }
        return this.realmCode;
    }

    /**
     * Gets the value of the typeId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setTypeId(II value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getTemplateId() {
        if (templateId == null) {
            templateId = new ArrayList<II>();
        }
        return this.templateId;
    }

    /**
     * Gets the value of the coveredPartyAsPatientId property.
     * 
     * @return
     *     possible object is
     *     {@link QUCRMT200000BCCoveredPartyAsPatient }
     *     
     */
    public QUCRMT200000BCCoveredPartyAsPatient getCoveredPartyAsPatientId() {
        return coveredPartyAsPatientId;
    }

    /**
     * Sets the value of the coveredPartyAsPatientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link QUCRMT200000BCCoveredPartyAsPatient }
     *     
     */
    public void setCoveredPartyAsPatientId(QUCRMT200000BCCoveredPartyAsPatient value) {
        this.coveredPartyAsPatientId = value;
    }

    /**
     * Gets the value of the policyOrAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link QUCRMT200000BCPolicyOrAccount }
     *     
     */
    public QUCRMT200000BCPolicyOrAccount getPolicyOrAccountId() {
        return policyOrAccountId;
    }

    /**
     * Sets the value of the policyOrAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link QUCRMT200000BCPolicyOrAccount }
     *     
     */
    public void setPolicyOrAccountId(QUCRMT200000BCPolicyOrAccount value) {
        this.policyOrAccountId = value;
    }

}
