//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.05 at 09:56:19 AM PDT 
//


package org.hl7.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QUPA_MT101103BC.QueryByParameterPayload complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QUPA_MT101103BC.QueryByParameterPayload">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/>
 *         &lt;element name="person.addr" type="{urn:hl7-org:v3}QUPA_MT101103BC.Person.addr" minOccurs="0"/>
 *         &lt;element name="person.administrativeGender" type="{urn:hl7-org:v3}QUPA_MT101103BC.Person.administrativeGender" minOccurs="0"/>
 *         &lt;element name="person.birthTime" type="{urn:hl7-org:v3}QUPA_MT101103BC.Person.birthTime" minOccurs="0"/>
 *         &lt;element name="person.deceasedTime" type="{urn:hl7-org:v3}QUPA_MT101103BC.Person.deceasedTime" minOccurs="0"/>
 *         &lt;element name="person.id" type="{urn:hl7-org:v3}QUPA_MT101103BC.Person.id" minOccurs="0"/>
 *         &lt;element name="person.name" type="{urn:hl7-org:v3}QUPA_MT101103BC.Person.name" minOccurs="0"/>
 *         &lt;element name="person.telecom" type="{urn:hl7-org:v3}QUPA_MT101103BC.Person.telecom" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:hl7-org:v3}InfrastructureRootAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QUPA_MT101103BC.QueryByParameterPayload", propOrder = {
    "realmCode",
    "typeId",
    "templateId",
    "personAddr",
    "personAdministrativeGender",
    "personBirthTime",
    "personDeceasedTime",
    "personId",
    "personName",
    "personTelecom"
})
public class QUPAMT101103BCQueryByParameterPayload {

    protected List<CS> realmCode;
    protected II typeId;
    protected List<II> templateId;
    @XmlElementRef(name = "person.addr", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<QUPAMT101103BCPersonAddr> personAddr;
    @XmlElementRef(name = "person.administrativeGender", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<QUPAMT101103BCPersonAdministrativeGender> personAdministrativeGender;
    @XmlElementRef(name = "person.birthTime", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<QUPAMT101103BCPersonBirthTime> personBirthTime;
    @XmlElementRef(name = "person.deceasedTime", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<QUPAMT101103BCPersonDeceasedTime> personDeceasedTime;
    @XmlElementRef(name = "person.id", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<QUPAMT101103BCPersonId> personId;
    @XmlElementRef(name = "person.name", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<QUPAMT101103BCPersonName> personName;
    @XmlElementRef(name = "person.telecom", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<QUPAMT101103BCPersonTelecom> personTelecom;

    /**
     * Gets the value of the realmCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the realmCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealmCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CS }
     * 
     * 
     */
    public List<CS> getRealmCode() {
        if (realmCode == null) {
            realmCode = new ArrayList<CS>();
        }
        return this.realmCode;
    }

    /**
     * Gets the value of the typeId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setTypeId(II value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getTemplateId() {
        if (templateId == null) {
            templateId = new ArrayList<II>();
        }
        return this.templateId;
    }

    /**
     * Gets the value of the personAddr property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link QUPAMT101103BCPersonAddr }{@code >}
     *     
     */
    public JAXBElement<QUPAMT101103BCPersonAddr> getPersonAddr() {
        return personAddr;
    }

    /**
     * Sets the value of the personAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link QUPAMT101103BCPersonAddr }{@code >}
     *     
     */
    public void setPersonAddr(JAXBElement<QUPAMT101103BCPersonAddr> value) {
        this.personAddr = value;
    }

    /**
     * Gets the value of the personAdministrativeGender property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link QUPAMT101103BCPersonAdministrativeGender }{@code >}
     *     
     */
    public JAXBElement<QUPAMT101103BCPersonAdministrativeGender> getPersonAdministrativeGender() {
        return personAdministrativeGender;
    }

    /**
     * Sets the value of the personAdministrativeGender property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link QUPAMT101103BCPersonAdministrativeGender }{@code >}
     *     
     */
    public void setPersonAdministrativeGender(JAXBElement<QUPAMT101103BCPersonAdministrativeGender> value) {
        this.personAdministrativeGender = value;
    }

    /**
     * Gets the value of the personBirthTime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link QUPAMT101103BCPersonBirthTime }{@code >}
     *     
     */
    public JAXBElement<QUPAMT101103BCPersonBirthTime> getPersonBirthTime() {
        return personBirthTime;
    }

    /**
     * Sets the value of the personBirthTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link QUPAMT101103BCPersonBirthTime }{@code >}
     *     
     */
    public void setPersonBirthTime(JAXBElement<QUPAMT101103BCPersonBirthTime> value) {
        this.personBirthTime = value;
    }

    /**
     * Gets the value of the personDeceasedTime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link QUPAMT101103BCPersonDeceasedTime }{@code >}
     *     
     */
    public JAXBElement<QUPAMT101103BCPersonDeceasedTime> getPersonDeceasedTime() {
        return personDeceasedTime;
    }

    /**
     * Sets the value of the personDeceasedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link QUPAMT101103BCPersonDeceasedTime }{@code >}
     *     
     */
    public void setPersonDeceasedTime(JAXBElement<QUPAMT101103BCPersonDeceasedTime> value) {
        this.personDeceasedTime = value;
    }

    /**
     * Gets the value of the personId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link QUPAMT101103BCPersonId }{@code >}
     *     
     */
    public JAXBElement<QUPAMT101103BCPersonId> getPersonId() {
        return personId;
    }

    /**
     * Sets the value of the personId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link QUPAMT101103BCPersonId }{@code >}
     *     
     */
    public void setPersonId(JAXBElement<QUPAMT101103BCPersonId> value) {
        this.personId = value;
    }

    /**
     * Gets the value of the personName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link QUPAMT101103BCPersonName }{@code >}
     *     
     */
    public JAXBElement<QUPAMT101103BCPersonName> getPersonName() {
        return personName;
    }

    /**
     * Sets the value of the personName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link QUPAMT101103BCPersonName }{@code >}
     *     
     */
    public void setPersonName(JAXBElement<QUPAMT101103BCPersonName> value) {
        this.personName = value;
    }

    /**
     * Gets the value of the personTelecom property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link QUPAMT101103BCPersonTelecom }{@code >}
     *     
     */
    public JAXBElement<QUPAMT101103BCPersonTelecom> getPersonTelecom() {
        return personTelecom;
    }

    /**
     * Sets the value of the personTelecom property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link QUPAMT101103BCPersonTelecom }{@code >}
     *     
     */
    public void setPersonTelecom(JAXBElement<QUPAMT101103BCPersonTelecom> value) {
        this.personTelecom = value;
    }

}
