//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.05 at 09:56:19 AM PDT 
//


package org.hl7.v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for x_FullAddressPartType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="x_FullAddressPartType">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="SAL"/>
 *     &lt;enumeration value="CNT"/>
 *     &lt;enumeration value="CTY"/>
 *     &lt;enumeration value="STA"/>
 *     &lt;enumeration value="ZIP"/>
 *     &lt;enumeration value="DIR"/>
 *     &lt;enumeration value="STR"/>
 *     &lt;enumeration value="STB"/>
 *     &lt;enumeration value="STTYP"/>
 *     &lt;enumeration value="ADL"/>
 *     &lt;enumeration value="UNID"/>
 *     &lt;enumeration value="UNIT"/>
 *     &lt;enumeration value="BNR"/>
 *     &lt;enumeration value="BNN"/>
 *     &lt;enumeration value="BNS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "x_FullAddressPartType")
@XmlEnum
public enum XFullAddressPartType {

    SAL,
    CNT,
    CTY,
    STA,
    ZIP,
    DIR,
    STR,
    STB,
    STTYP,
    ADL,
    UNID,
    UNIT,
    BNR,
    BNN,
    BNS;

    public String value() {
        return name();
    }

    public static XFullAddressPartType fromValue(String v) {
        return valueOf(v);
    }

}
